name: Athar Health Bot

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # تحديث للإصدار الرابع
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # استخدام توكن النظام مباشرة

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python update_tips.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add athardata.json
          git commit -m "تحديث طبي تلقائي 🔬" || exit 0
          git pull --rebase origin main # ضمان عدم وجود تعارض
          git push origin main
