name: Health Data Auto Bot

on:
  schedule:
    - cron: '0 */12 * * *' # هادي معناها كل 12 ساعة بالدقيقة والثانية
  workflow_dispatch: # هادي معناها نقدروا نشغلوه يدوياً للتجربة

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bot Script
        run: python update_health_data.py
      - name: Save and Push
        run: |
          git config --global user.name "Athar-Bot"
          git config --global user.email "bot@athar.ly"
          git add .
          git commit -m "تحديث تلقائي وأرشفة [Bot]" || exit 0
          git push
